In [ ]:
import pandas as pd

from google.colab import files

chukyo = pd.read_csv('/content/drive/MyDrive/IntegratedDB_DoNotTouch/Chukyo.csv')
higas = pd.read_csv('/content/drive/MyDrive/IntegratedDB_DoNotTouch/Higashisurugawan.csv')
kyushu = pd.read_csv('/content/drive/MyDrive/IntegratedDB_DoNotTouch/Kyushu.csv')
tokyo = pd.read_csv('/content/drive/MyDrive/IntegratedDB_DoNotTouch/Tokyo.csv')
sample_s = pd.read_csv('/content/drive/MyDrive/IntegratedDB_DoNotTouch/sample_submission.csv')
data_s = pd.read_csv('/content/drive/MyDrive/IntegratedDB_DoNotTouch/Data_Specification.csv')
test_f = pd.read_csv('/content/drive/MyDrive/IntegratedDB_DoNotTouch/test.csv')
chukyo_zone_features = pd.read_csv('/content/drive/MyDrive/IntegratedDB_DoNotTouch/Chukyo_zone_feature_area.csv')
higas_zone_features = pd.read_csv('/content/drive/MyDrive/IntegratedDB_DoNotTouch/Higashisurugawan_zone_feature_area.csv')
kyushu_zone_features = pd.read_csv('/content/drive/MyDrive/IntegratedDB_DoNotTouch/Kyushu_zone_feature_area.csv')
tokyo_zone_features = pd.read_csv('/content/drive/MyDrive/IntegratedDB_DoNotTouch/Tokyo_zone_feature_area.csv')
kinki_zone_features = pd.read_csv('/content/drive/MyDrive/IntegratedDB_DoNotTouch/Kinki_zone_feature_area.csv')

chukyo_copy = chukyo.copy()
higas_copy = higas.copy()
kyushu_copy = kyushu.copy()
tokyo_copy = tokyo.copy()
sample_copy = sample_s.copy()
data_copy = data_s.copy()
test_copy = test_f.copy()
chukyo_zone_features_copy = chukyo_zone_features.copy()
higas_zone_features_copy = higas_zone_features.copy()
kyushu_zone_features_copy = kyushu_zone_features.copy()
tokyo_zone_features_copy = tokyo_zone_features.copy()
kinki_zone_features_copy = kinki_zone_features.copy()

import pandas as pd

df = pd.DataFrame(data_copy)

cities = ['Tokyo', 'Chukyo']
labels = ['Occupation', 'Trip Type']

tokyo_occupation = df[(df['City'] == cities[0]) & (df['Type'] == labels[0])]
tokyo_trip = df[(df['City'] == cities[0]) & (df['Type'] == labels[1])]

chukyo_occupation = df[(df['City'] == cities[1]) & (df['Type'] == labels[0])]
chukyo_trip = df[(df['City'] == cities[1]) & (df['Type'] == labels[1])]

occupation = df[(df['Type'] == labels[0])]
trip = df[(df['Type'] == labels[1])]

# Get unique values in the 'Category' column and assign unique integers
occupation['Occupation_Encoded'] = pd.factorize(occupation['Description'])[0]
trip['Trip_Encoded'] = pd.factorize(trip['Description'])[0]

occupation = occupation.drop('City', axis=1)
occupation = occupation.drop('Type', axis=1)
occupation = occupation.drop('Code', axis=1)

trip = trip.drop('Code', axis=1)
trip = trip.drop('City', axis=1)
trip = trip.drop('Type', axis=1)

tokyo_occupation.rename(columns={'Code': 'Occupation'}, inplace=True)
tokyo_trip.rename(columns={'Code': 'Trip_type'}, inplace=True)

chukyo_occupation.rename(columns={'Code': 'Occupation'}, inplace=True)
chukyo_trip.rename(columns={'Code': 'Trip_type'}, inplace=True)

# Convert to int
tokyo_copy['Occupation'] = tokyo_copy['Occupation'].astype(int)
chukyo_copy['Occupation'] = chukyo_copy['Occupation'].astype(int)

tokyo_copy['Trip_type'] = tokyo_copy['Trip_type'].astype(int)
chukyo_copy['Trip_type'] = chukyo_copy['Trip_type'].astype(int)

tokyo_occupation['Occupation'] = tokyo_occupation['Occupation'].astype(int)
chukyo_occupation['Occupation'] = chukyo_occupation['Occupation'].astype(int)

tokyo_trip['Trip_type'] = tokyo_trip['Trip_type'].astype(int)
chukyo_trip['Trip_type'] = chukyo_trip['Trip_type'].astype(int)

tokyo_modified = pd.merge(tokyo_copy, tokyo_occupation, on='Occupation', how='inner')
tokyo_modified = tokyo_modified.drop('Occupation', axis=1)
tokyo_modified = tokyo_modified.drop('Type', axis=1)
tokyo_modified = tokyo_modified.drop('City', axis=1)
tokyo_modified.rename(columns={'Description': 'Occupation'}, inplace=True)

chukyo_modified = pd.merge(chukyo_copy, chukyo_occupation, on='Occupation', how='inner')
chukyo_modified = chukyo_modified.drop('Occupation', axis=1)
chukyo_modified = chukyo_modified.drop('Type', axis=1)
chukyo_modified = chukyo_modified.drop('City', axis=1)
chukyo_modified.rename(columns={'Description': 'Occupation'}, inplace=True)

tokyo_modified = pd.merge(tokyo_modified, tokyo_trip, on='Trip_type', how='inner')
tokyo_modified = tokyo_modified.drop('Trip_type', axis=1)
tokyo_modified.rename(columns={'Description': 'Trip_type'}, inplace=True)
tokyo_modified = tokyo_modified.drop('Type', axis=1)

chukyo_modified = pd.merge(chukyo_modified, chukyo_trip, on='Trip_type', how='inner')
chukyo_modified = chukyo_modified.drop('Trip_type', axis=1)
chukyo_modified.rename(columns={'Description': 'Trip_type'}, inplace=True)
chukyo_modified = chukyo_modified.drop('Type', axis=1)

tokyo_features = tokyo_zone_features_copy.rename(columns={'ZONE_ID': 'Destination'})
chukyo_features = chukyo_zone_features_copy.rename(columns={'ZONE_ID': 'Destination'})

tokyo_modified = pd.merge(tokyo_modified, tokyo_features, on='Destination', how='inner')
chukyo_modified = pd.merge(chukyo_modified, chukyo_features, on='Destination', how='inner')

tokyo_modified.rename(columns={'T000918002': 'Number of business establishments (secondary sector of industry)', 'T000918006' : 'Number of employees (secondary sector of industry)', 'T000918021' : 'Number of business establishments (tertiary sector of industry)', 'T000918025' : 'Number of employees (tertiary sector of industry)', 'T000847001' : 'Night Population' }, inplace=True)
chukyo_modified.rename(columns={'T000918002': 'Number of business establishments (secondary sector of industry)', 'T000918006' : 'Number of employees (secondary sector of industry)', 'T000918021' : 'Number of business establishments (tertiary sector of industry)', 'T000918025' : 'Number of employees (tertiary sector of industry)', 'T000847001' : 'Night Population' }, inplace=True)

occupation_rename = occupation.rename(columns={'Description': 'Occupation'})

tokyo_modified = pd.merge(tokyo_modified, occupation_rename, on='Occupation', how='inner')
chukyo_modified = pd.merge(chukyo_modified, occupation_rename, on='Occupation', how='inner')

trip_rename = trip.rename(columns={'Description': 'Trip_type'})

tokyo_modified = pd.merge(tokyo_modified, trip_rename, on='Trip_type', how='inner')
chukyo_modified = pd.merge(chukyo_modified, trip_rename, on='Trip_type', how='inner')

chukyo_modified = chukyo_modified.drop_duplicates()

<ipython-input-22-f2853fc63646>:48: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  occupation['Occupation_Encoded'] = pd.factorize(occupation['Description'])[0]
<ipython-input-22-f2853fc63646>:49: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trip['Trip_Encoded'] = pd.factorize(trip['Description'])[0]
<ipython-input-22-f2853fc63646>:59: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tokyo_occupation.rename(columns={'Code': 'Occupation'}, inplace=True)
<ipython-input-22-f2853fc63646>:60: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tokyo_trip.rename(columns={'Code': 'Trip_type'}, inplace=True)
<ipython-input-22-f2853fc63646>:62: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chukyo_occupation.rename(columns={'Code': 'Occupation'}, inplace=True)
<ipython-input-22-f2853fc63646>:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chukyo_trip.rename(columns={'Code': 'Trip_type'}, inplace=True)
<ipython-input-22-f2853fc63646>:72: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tokyo_occupation['Occupation'] = tokyo_occupation['Occupation'].astype(int)
<ipython-input-22-f2853fc63646>:73: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chukyo_occupation['Occupation'] = chukyo_occupation['Occupation'].astype(int)
<ipython-input-22-f2853fc63646>:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tokyo_trip['Trip_type'] = tokyo_trip['Trip_type'].astype(int)
<ipython-input-22-f2853fc63646>:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chukyo_trip['Trip_type'] = chukyo_trip['Trip_type'].astype(int)

*Reading Files from the drive and creating a copy of each DS*

In [ ]:
#reading the text file
data_path = '/content/drive/MyDrive/IntegratedDB_DoNotTouch/feature_description.txt'

with open(data_path) as fid:
    data = "Dummy String"
    while data:
        data = fid.readline()
        # print(data)

In [ ]:
# chukyo_zone_features_copy

In [ ]:
chukyo_zone_features_copy['Destination_New'] =  range(0, 1009)

In [ ]:
czp = chukyo_zone_features_copy[['Destination_New', 'ZONE_ID']]
czp.rename(columns={'ZONE_ID': 'Destination'}, inplace=True)

<ipython-input-26-70193c7c7148>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  czp.rename(columns={'ZONE_ID': 'Destination'}, inplace=True)

In [ ]:
czp =czp.drop_duplicates()

In [ ]:
chukyo_modified = pd.merge(chukyo_modified, czp, on='Destination', how='inner')
len(chukyo_modified)

205435

In [ ]:
chukyo_modified.head()

,Pid,Departure_time,Gender,Age,Origin,Destination,Occupation,City,Trip_type,Number of business establishments (secondary sector of industry),Number of employees (secondary sector of industry),Number of business establishments (tertiary sector of industry),Number of employees (tertiary sector of industry),Night Population,Occupation_Encoded,Trip_Encoded,Destination_New
0,176887,2011/10/03 09:30:00,2,11,1507,1503,Services,Chukyo,To Cram/Private School,30.464779,185.587571,252.796691,1391.760649,7920.976128,3,18,231
1,175380,2011/10/03 17:40:00,2,1,1512,1503,Preschoolers Elementary and Middle School Stud...,Chukyo,To Cram/Private School,30.464779,185.587571,252.796691,1391.760649,7920.976128,10,18,231
2,175141,2011/10/03 16:15:00,2,2,1502,1503,Preschoolers Elementary and Middle School Stud...,Chukyo,To Cram/Private School,30.464779,185.587571,252.796691,1391.760649,7920.976128,10,18,231
3,176613,2011/10/03 16:40:00,2,1,1504,1503,Preschoolers Elementary and Middle School Stud...,Chukyo,To Cram/Private School,30.464779,185.587571,252.796691,1391.760649,7920.976128,10,18,231
4,177736,2011/10/03 15:20:00,1,1,1507,1503,Preschoolers Elementary and Middle School Stud...,Chukyo,To Cram/Private School,30.464779,185.587571,252.796691,1391.760649,7920.976128,10,18,231

In [ ]:
chukyo_modified['Departure_time'] = pd.to_datetime(chukyo_modified['Departure_time'])
chukyo_modified['Departure_time'] = chukyo_modified['Departure_time'].dt.time

In [ ]:
chukyo_modified = chukyo_modified.sort_values(by='Departure_time', ascending=True)

In [ ]:
# Convert the 'TimeOnly' column to a string with a custom format
chukyo_modified['Departure_time'] = chukyo_modified['Departure_time'].apply(lambda x: x.strftime('%H'))

In [ ]:
# Creating training and testing sets.
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

chukyo_df = pd.DataFrame(chukyo_modified)

# X = pd.DataFrame(data.data, columns=data.feature_names)
# y = (data.target == 0).astype(int)  # Binary classification: Setosa vs. Not Setosa
result = chukyo_df['Destination_New'].values
input = chukyo_df.drop('Destination_New', axis=1, inplace=False)

In [ ]:
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(chukyo_df, result, test_size=0.2, random_state=42)

Feature Engineering.

In [ ]:
X_train.head()

,Pid,Departure_time,Gender,Age,Origin,Destination,Occupation,City,Trip_type,Number of business establishments (secondary sector of industry),Number of employees (secondary sector of industry),Number of business establishments (tertiary sector of industry),Number of employees (tertiary sector of industry),Night Population,Occupation_Encoded,Trip_Encoded,Destination_New
56005,75776,09,2,9,11505,11501,Clerical Assistants,Chukyo,To Hospital,26.243628,270.186933,345.286391,2114.041245,5851.467590,6,6,370
203074,7616,09,2,12,22105,22105,Argriculture Forestry and Fishery,Chukyo,For Volunteer Activity,2.739445,4.511598,65.983205,46.991238,226.561027,0,23,884
3604,172849,15,1,1,1406,1406,Preschoolers Elementary and Middle School Stud...,Chukyo,To Eat,24.337923,176.922219,137.061855,1339.214754,7391.851698,10,19,214
122908,59428,15,2,12,13227,13225,Inoccupation,Chukyo,Farm Chores,11.202362,51.853800,169.574598,1156.031855,2101.522071,14,12,551
163789,21757,06,1,8,14202,508,Clerical Assistants,Chukyo,To Home,94.048304,868.598654,1232.050617,14661.599870,10855.677514,6,2,68

In [ ]:
x_train_dropped = X_train.drop(['Occupation', 'City', 'Trip_type', 'Destination'], axis=1)

In [ ]:
x_train_dropped

,Pid,Departure_time,Gender,Age,Origin,Number of business establishments (secondary sector of industry),Number of employees (secondary sector of industry),Number of business establishments (tertiary sector of industry),Number of employees (tertiary sector of industry),Night Population,Occupation_Encoded,Trip_Encoded,Destination_New
56005,75776,09,2,9,11505,26.243628,270.186933,345.286391,2114.041245,5851.467590,6,6,370
203074,7616,09,2,12,22105,2.739445,4.511598,65.983205,46.991238,226.561027,0,23,884
3604,172849,15,1,1,1406,24.337923,176.922219,137.061855,1339.214754,7391.851698,10,19,214
122908,59428,15,2,12,13227,11.202362,51.853800,169.574598,1156.031855,2101.522071,14,12,551
163789,21757,06,1,8,14202,94.048304,868.598654,1232.050617,14661.599870,10855.677514,6,2,68
...,...,...,...,...,...,...,...,...,...,...,...,...,...
152319,56845,10,1,12,13005,1.767148,2.104433,20.656292,12.819865,124.515510,14,7,524
201170,122688,09,1,16,30906,0.970700,2.642622,26.545128,19.990733,81.074694,14,6,1008
58333,46277,11,1,6,14801,41.461267,222.313394,418.420655,1850.571188,5964.440041,3,19,718
133186,48193,12,1,16,10202,35.442676,198.270606,279.390559,1501.091981,5516.637567,14,10,269
105070,105207,10,2,13,12304,7.657547,27.033126,204.915011,221.498572,1264.269302,13,6,457

In [ ]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectKBest, chi2, f_classif, RFE
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.feature_selection import SelectFromModel
from sklearn.tree import DecisionTreeClassifier
from sklearn.pipeline import Pipeline

# Load sample dataset (you can replace this with your own dataset)
# data = load_iris()
# X, y =  X_train.drop(['Occupation', 'City', 'Trip_type'], axis=1), data.target

# Split the data into training and testing sets
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


# 1. Correlation Analysis
# correlation_matrix = np.corrcoef(x_train_dropped, rowvar=False)
# highly_correlated_features = np.where(np.abs(correlation_matrix) > 0.8)

# 2. Univariate Feature Selection
k_best = 2  # You can adjust this based on the number of features you want to select
selector = SelectKBest(score_func=f_classif, k=k_best)
X_train_univariate = selector.fit_transform(x_train_dropped, y_train)
selected_features_univariate = np.where(selector.get_support())[0]

# 3. Recursive Feature Elimination (RFE)
model = RandomForestClassifier(n_estimators=10)
rfe_selector = RFE(model, n_features_to_select=k_best)
X_train_rfe = rfe_selector.fit_transform(x_train_dropped, y_train)
selected_features_rfe = np.where(rfe_selector.support_)[0]

# 4. Tree-based Methods
tree_model = RandomForestClassifier(n_estimators=10)
tree_model.fit(x_train_dropped, y_train)
importances = tree_model.feature_importances_
selected_features_tree = np.argsort(importances)[-k_best:]

# 6. Principal Component Analysis (PCA)
pca = PCA(n_components=k_best)
X_train_pca = pca.fit_transform(x_train_dropped)
selected_features_pca = pca.components_.argsort()[:, -k_best:]

/usr/local/lib/python3.10/dist-packages/sklearn/feature_selection/_univariate_selection.py:113: RuntimeWarning: divide by zero encountered in divide
  f = msb / msw

In [ ]:
from sklearn.feature_selection import mutual_info_classif

# 7. Information Gain and Entropy (SelectKBest with mutual_info_classif)
selector_info_gain = SelectKBest(score_func=mutual_info_classif, k=k_best)
X_train_info_gain = selector_info_gain.fit_transform(x_train_dropped, y_train)
selected_features_info_gain = np.where(selector_info_gain.get_support())[0]

In [ ]:
# 8. Feature Importance from Embedded Methods (SelectFromModel)
embed_model = DecisionTreeClassifier()
embed_selector = SelectFromModel(embed_model)
X_train_embed = embed_selector.fit_transform(x_train_dropped, y_train)
selected_features_embed = np.where(embed_selector.get_support())[0]

In [ ]:
# 5. LASSO Regression
lasso_model = LogisticRegression(penalty='l1', solver='liblinear')
scaler = StandardScaler()
lasso_pipeline = Pipeline([('scaler', scaler), ('lasso', lasso_model)])
lasso_pipeline.fit(x_train_dropped, y_train)
selected_features_lasso = np.where(lasso_model.coef_[0] != 0)[0]

In [ ]:
# Display selected features for each method
# print("Selected features using Correlation Analysis:", highly_correlated_features)
print("Selected features using Univariate Feature Selection:", selected_features_univariate)
print("Selected features using Recursive Feature Elimination (RFE):", selected_features_rfe)
print("Selected features using Tree-based Methods:", selected_features_tree)
# print("Selected features using LASSO Regression:", selected_features_lasso)
print("Selected features using Principal Component Analysis (PCA):", selected_features_pca)
# print("Selected features using Information Gain and Entropy:", selected_features_info_gain)
# print("Selected features using Feature Importance from Embedded Methods:", selected_features_embed)

Selected features using Univariate Feature Selection: [ 5 12]
Selected features using Recursive Feature Elimination (RFE): [6 8]
Selected features using Tree-based Methods: [6 7]
Selected features using Principal Component Analysis (PCA): [[8 0]
 [7 8]]

In [ ]:
# Assuming your data is in a Pandas DataFrame
feature_names = data.feature_names

# Display selected features for each method with names
# print("Selected features using Correlation Analysis:")
# print([feature_names[i] for i in highly_correlated_features[0]])

print("Selected features using Univariate Feature Selection:")
print([feature_names[i] for i in selected_features_univariate])

print("Selected features using Recursive Feature Elimination (RFE):")
print([feature_names[i] for i in selected_features_rfe])

print("Selected features using Tree-based Methods:")
print([feature_names[i] for i in selected_features_tree])

print("Selected features using LASSO Regression:")
print([feature_names[i] for i in selected_features_lasso])

print("Selected features using Principal Component Analysis (PCA):")
print([feature_names[i] for i in selected_features_pca[0]])

print("Selected features using Information Gain and Entropy:")
print([feature_names[i] for i in selected_features_info_gain])

print("Selected features using Feature Importance from Embedded Methods:")
print([feature_names[i] for i in selected_features_embed])

In [ ]:
from sklearn.feature_selection import RFE
from sklearn.ensemble import RandomForestClassifier

x_train_dropped = X_train.drop(['Occupation', 'City', 'Trip_type'], axis=1)

# here as well, use the model that you finalize to use!

model = RandomForestClassifier()
rfe = RFE(model, n_features_to_select=8)
X_selected = rfe.fit_transform(x_train_dropped, y_train)

In [ ]:
X_selected

array([[11505, 11501, 26.243627677978743, ..., 2114.041245158868,
        5851.467590247103, 370],
       [22105, 22105, 2.7394446942543773, ..., 46.99123828558346,
        226.5610270504436, 884],
       [1406, 1406, 24.337923154858856, ..., 1339.2147535820095,
        7391.851698350418, 214],
       ...,
       [14801, 15106, 41.461267122113256, ..., 1850.5711883779215,
        5964.440041379223, 718],
       [10202, 10202, 35.44267563115581, ..., 1501.0919814290191,
        5516.637566574564, 269],
       [12304, 12304, 7.657547122458222, ..., 221.4985721255555,
        1264.2693018752536, 457]], dtype=object)

In [ ]:
from sklearn.feature_selection import SelectKBest, chi2

X_new = SelectKBest(chi2, k=10).fit_transform(x_train_dropped, y_train)

In [ ]:
X_new

array([[75776, 11505, 11501, ..., 5851.467590247103, 6, 370],
       [7616, 22105, 22105, ..., 226.5610270504436, 23, 884],
       [172849, 1406, 1406, ..., 7391.851698350418, 19, 214],
       ...,
       [46277, 14801, 15106, ..., 5964.440041379223, 19, 718],
       [48193, 10202, 10202, ..., 5516.637566574564, 10, 269],
       [105207, 12304, 12304, ..., 1264.2693018752536, 6, 457]],
      dtype=object)

In [ ]:
from sklearn.linear_model import Lasso

lasso = Lasso(alpha=0.01)
lasso.fit(x_train_dropped, y_train)

Lasso(alpha=0.01)

In [ ]:
from sklearn.feature_selection import mutual_info_classif

mi = mutual_info_classif(x_train_dropped, y_train)

In [ ]:
mi

array([3.01304043, 0.0635242 , 0.01619236, 0.0877271 , 2.94407234,
       6.64265001, 6.64275284, 6.64259312, 6.64255215, 6.64262131,
       6.64264575, 0.15078954, 0.16181232, 6.64274219])

Cross-validation is a technique used to assess how well a model will generalize to an independent dataset. It helps to ensure that your model is not overfitting to the training data. Here's a general outline of how you can use cross-validation in combination with feature selection and model training:

You can adapt this template to use different classifiers, feature selection methods, and evaluation metrics based on your specific needs. Keep in mind that the number of features selected (n_features_to_select in the example) and other hyperparameters should be fine-tuned based on the characteristics of your dataset.

Remember to replace the RandomForestClassifier and RFE with the classifier and feature selection method you find most suitable for your problem. Adjust the number of splits in the cross-validation (n_splits) based on the size of your dataset.

This will give you an array of accuracy scores for each fold, as well as the mean accuracy across all folds.

In [ ]:
from sklearn.model_selection import cross_val_score, StratifiedKFold
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import RFE

# use the model that you finalize
model = RandomForestClassifier()
rfe = RFE(model, n_features_to_select=5)

# Assuming X is your feature matrix and y is your target variable

# Feature selection using RFE
X_selected = rfe.fit_transform(x_train_dropped, y_train)

In [ ]:


# Initialize cross-validation
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# Perform cross-validation with the selected features
scores = cross_val_score(model, X_selected, y_train, cv=cv, scoring='accuracy')

print("Cross-Validation Scores:", scores)
print("Mean Accuracy:", scores.mean())

/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(

Cross-Validation Scores: [1.         0.99996958 0.99993915 1.         1.        ]
Mean Accuracy: 0.9999817462731974

In [ ]:
# Create and train an XGBoost classifier for multiclass classification
import xgboost as xgb
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_train = le.fit_transform(y_train)
X_train['Departure_time'] = le.fit_transform(X_train['Departure_time'].astype(str))
X_train['Occupation'] = le.fit_transform(X_train['Occupation'].astype(str))
X_train['City'] = le.fit_transform(X_train['City'].astype(str))
X_train['Trip_type'] = le.fit_transform(X_train['Trip_type'].astype(str))
model = xgb.XGBClassifier(objective="multi:softprob", num_class=1006)  # "multi:softprob" for multiclass
model.fit(X_train, y_train)

In [ ]:
from sklearn.metrics import classification_report

# Make predictions on the test set
X_test['Departure_time'] = le.fit_transform(X_test['Departure_time'].astype(str))
X_test['Occupation'] = le.fit_transform(X_test['Occupation'].astype(str))
X_test['City'] = le.fit_transform(X_test['City'].astype(str))
X_test['Trip_type'] = le.fit_transform(X_test['Trip_type'].astype(str))
y_pred = model.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Generate a classification report

# class_names = data.target_names
report = classification_report(y_test, y_pred)
print("Classification Report:\n", report)

In [ ]:
from sklearn.metrics import mean_squared_error
import numpy as np

# Calculate mean squared error
mse = mean_squared_error(y_test, y_pred)

# Calculate root mean squared error
rmse = np.sqrt(mse)

print("Mean Squared Error:", mse)
print("Root Mean Squared Error:", rmse)

Mean Squared Error: 118272.18132255945
Root Mean Squared Error: 343.9072277847028

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report, confusion_matrix


# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.2f}')

# Calculate precision
precision = precision_score(y_test, y_pred, average='weighted', zero_division=1)
print(f'Precision: {precision:.2f}')

# Calculate recall
recall = recall_score(y_test, y_pred, average='weighted', zero_division=1)
print(f'Recall: {recall:.2f}')

# Calculate F1 score
f1 = f1_score(y_test, y_pred, average='weighted', zero_division=1)
print(f'F1 Score: {f1:.2f}')

# Display classification report
# print('Classification Report:')
# print(classification_report(y_test, y_pred))

# Display confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print('Confusion Matrix:')
print(conf_matrix)

Accuracy: 0.25
Precision: 0.93
Recall: 0.25
F1 Score: 0.21
Confusion Matrix:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

In [ ]:
# FOR REFERENCE OF HYPER PARAMETER TUNNING.

import xgboost as xgb
from sklearn.model_selection import GridSearchCV

# Define the parameter grid for grid search
param_grid = {
    'learning_rate': [0.01, 0.1, 0.3],
    'n_estimators': [100, 200, 300],
    'max_depth': [3, 4, 5],
    'min_child_weight': [1, 2, 3],
    'gamma': [0, 0.1, 0.2],
    'subsample': [0.8, 0.9, 1.0],
    'colsample_bytree': [0.8, 0.9, 1.0]
}


# Create an XGBoost classifier
model = xgb.XGBClassifier(objective="multi:softprob", num_class=1009)

# Perform grid search with cross-validation
grid_search = GridSearchCV(estimator=model, param_grid=param_grid, cv=3, n_jobs=5, verbose=1)
grid_search.fit(X_train, y_train)

# Get the best hyperparameters
best_params = grid_search.best_params_
print("Best Hyperparameters:", best_params)

# Train a model with the best hyperparameters
best_model = xgb.XGBClassifier(objective="multi:softprob", num_class=3, **best_params)
best_model.fit(X_train, y_train)

# Make predictions and evaluate the model
y_pred = best_model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy with Best Hyperparameters:", accuracy)

In [ ]:
# Import the necessary libraries
import xgboost as xgb
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

# Load the Iris dataset
data = load_iris()
X = pd.DataFrame(data.data, columns=data.feature_names)
y = data.target  # Multiclass classification

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create and train an XGBoost classifier for multiclass classification
model = xgb.XGBClassifier(objective="multi:softprob", num_class=3)  # "multi:softprob" for multiclass
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Generate a classification report
class_names = data.target_names
report = classification_report(y_test, y_pred, target_names=class_names)
print("Classification Report:\n", report)

In [ ]:
y

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

# Create scatter plots for three pairs of features
plt.figure(figsize=(12, 6))

headval = 500000

plt.subplot(1, 3, 1)
plt.title("Chukyo City\nDeparture Time vs Night Population")
sns.scatterplot(data=chukyo_modified.head(headval), x="Departure_time", y="Night Population", hue="Destination")

plt.show()

In [ ]:
plt.subplot(1, 2, 1)
plt.title("Tokyo City\nDeparture Time vs Night Population")
sns.scatterplot(data=tokyo_modified.head(headval), x="Departure_time", y="Night Population", hue="Destination")

plt.show()

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

# Create scatter plots for three pairs of features
plt.figure(figsize=(12, 6))

headval = 500000

plt.subplot(1, 3, 1)
sns.scatterplot(data=tokyo_modified.head(headval), x="Age", y="Trip_Encoded", hue="Destination")
plt.title("Occupation vs Night Population")


plt.subplot(1, 3, 2)
sns.scatterplot(data=tokyo_modified.head(headval), x="Age", y="Night Population", hue="Destination")
plt.title("Age vs Night Population")


plt.subplot(1, 3, 3)
sns.scatterplot(data=tokyo_modified.head(headval), x="Gender", y="Night Population", hue="Destination")
plt.title("Gender vs Night Population")

# plt.tight_layout()

# Show the plots
plt.show()

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

plot_data = pd.DataFrame(chukyo_modified)
plt.figure(figsize=(24, 12))

# plt.subplot(1, 1, 1)
bp = sns.histplot(x="Age", y="Occupation", data=plot_data)
bp.set_xticklabels(bp.get_xticklabels(), rotation=45, ha="right")
# plt.title("Night Population Distribution by Trip Type at Hour 1")
plt.xlabel("Age")
plt.ylabel("Occupation")

plt.show()

# plt.subplot(2, 1, 1)
bp = sns.histplot(x="Departure_time", y="Occupation", data=chukyo_modified)
# bp.set_xticklabels(bp.get_xticklabels(), rotation=45, ha="right")
plt.xlabel("Age")
plt.ylabel("Occupation")
plt.show()

# plt.subplot(3, 1, 1)
bp = sns.histplot(x="Departure_time", y="Trip_type", data=plot_data)
# bp.set_xticklabels(bp.get_xticklabels(), rotation=45, ha="right")
plt.title("Night Population Distribution by Trip Type at Hour 1")
plt.xlabel("Departure_time")
plt.ylabel("Trip type")

plt.show()

In [ ]:
temp = chukyo_modified.rename(columns={'Number of business establishments (secondary sector of industry)': 'No. of II sector business.'}, inplace=False)
temp = temp.rename(columns={'Number of employees (secondary sector of industry)': 'Employees in II business'}, inplace=False)
temp = temp.rename(columns={'Number of business establishments (tertiary sector of industry)': 'No. of III sector business.'}, inplace=False)
temp = temp.rename(columns={'Number of employees (tertiary sector of industry)': 'Employees in III business'}, inplace=False)

In [ ]:
temp['Departure_time'] = pd.to_datetime(chukyo_modified['Departure_time'])


temp['Departure_time'] = temp['Departure_time'].dt.hour

# temp['Departure_time'] = temp['Departure_time'].dt.hour

In [ ]:
correlation_matrix1 = temp.corr()
plt.title("Chukyo City\n HeatMap of Correlation Matrix")
sns.heatmap(correlation_matrix1, annot=False, cmap="coolwarm")